[package]
name = "dijo"
version = "0.4.7"
authors = ["Parham Alvani <parham.alvani@gmail.com>", "Akshay <nerdy@peppe.rs>"]
edition = "2024"
description = "Scriptable, curses-based, digital habit tracker"
homepage = "https://github.com/1995parham/dijo"
repository = "https://github.com/1995parham/dijo"
readme = './readme.md'
keywords = ["tracker", "event-tracker", "tui", "journal"]
categories = ["date-and-time", "command-line-interface"]
license = "MIT"

[dependencies]
lazy_static = "1.4.0"
erased-serde = "0.4"
typetag = "0.2.21"
directories = "6.0.0"
toml = "0.9.8"
syn = "=2.0.106"
cursive = "0.21"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serde_json]
version = "1.0"
features = ["preserve_order"]

[dependencies.clap]
version = "4.5"
features = ["cargo"]
