[package]
name = "dijo"
version = "0.1.0"
authors = ["Akshay <nerdy@peppe.rs>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.14"
serde_json = "1.0"
lazy_static = "1.4.0"
erased-serde = "0.3"
typetag = "0.1.4"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.serde]
version = "1.0.103"
features = ["derive"]
