[package]
name = "track"
version = "0.1.0"
authors = ["Akshay <nerdypepper@tuta.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.14"
chrono = "0.4"
serde_json = "1.0"

[dependencies.serde]
version = "1.0.103"
features = ["derive"]
